services:
  backend:
    build: ./backend
    ports:
      - "3001:3001"
    volumes:
      - ./storage:/app/storage
      - ./backend/db:/app/backend/db
      - type: bind
        source: ./backend/.env
        target: /app/backend/.env
        bind:
          create_host_path: false

  frontend:
    build: ./frontend
    ports:
      - "5173:5173"
    depends_on:
      - backend
